# Generated by Django 4.1.3 on 2022-11-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('employment_date', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='uploads/% Y/% m/% d/')),
            ],
        ),
    ]
