# Generated by Django 4.1.3 on 2022-11-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherinfo',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='email',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='file',
            field=models.FileField(default=1, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='lastname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='owner',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
