# Generated by Django 4.1.3 on 2022-11-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_rename_name_teacherinfo_firstname_teacherinfo_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='file',
            field=models.FileField(upload_to='media/%y/%m'),
        ),
    ]
