# Generated by Django 4.1.3 on 2022-12-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacherinfo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='employment_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='file',
            field=models.FileField(null=True, upload_to='media/%y/%m'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='owner',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
