# Generated by Django 4.1.3 on 2022-12-06 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_teacherinfo_age_alter_teacherinfo_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinfo',
            name='owner',
        ),
    ]
