# Generated by Django 4.1.3 on 2022-11-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
        ('adminn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('student', models.ManyToManyField(to='student.studentinfo')),
                ('teacher', models.ManyToManyField(to='teacher.teacherinfo')),
            ],
        ),
        migrations.RenameModel(
            old_name='AdminInfo',
            new_name='AdminnInfo',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AddField(
            model_name='classinfo',
            name='student',
            field=models.ManyToManyField(to='student.studentinfo'),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='teacher',
            field=models.ManyToManyField(to='teacher.teacherinfo'),
        ),
    ]
