# Generated by Django 4.1.3 on 2022-11-13 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0002_subjectinfo_rename_admininfo_adminninfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectinfo',
            name='student',
        ),
        migrations.RemoveField(
            model_name='subjectinfo',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='ClassInfo',
        ),
        migrations.DeleteModel(
            name='SubjectInfo',
        ),
    ]
