# Generated by Django 4.1.3 on 2022-12-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0003_remove_subjectinfo_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
