# Generated by Django 4.1.3 on 2022-11-16 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjectinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectinfo',
            old_name='me',
            new_name='classroom',
        ),
    ]
