# Generated by Django 4.1.3 on 2022-11-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parentinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='uploads/% Y/% m/% d/')),
                ('child', models.ManyToManyField(to='student.studentinfo')),
            ],
        ),
    ]
