# Generated by Django 4.1.3 on 2022-11-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('year', models.DateField()),
                ('admission_id', models.CharField(max_length=7)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='uploads/% Y/% m/% d/')),
                ('DoB', models.DateField()),
                ('age', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True)),
            ],
        ),
    ]
