# Generated by Django 4.1.3 on 2022-11-13 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentinfo_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='classroom',
        ),
    ]
