# Generated by Django 4.1.3 on 2022-11-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studentinfo_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='admission_date',
            field=models.DateTimeField(),
        ),
    ]
