# Generated by Django 4.1.3 on 2022-11-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_studentinfo_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='admission_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
