# Generated by Django 4.1.3 on 2022-11-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
        ('subjectinfo', '0002_rename_me_subjectinfo_classroom'),
        ('classinfo', '0001_initial'),
        ('student', '0007_remove_studentinfo_classroom_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentInfo',
            new_name='Student',
        ),
    ]
