# Generated by Django 4.1.3 on 2022-11-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_rename_studentinfo_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='file',
            field=models.FileField(default=1, upload_to='uploads/%y/%m'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='firstname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='lastname',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
