# Generated by Django 4.1.3 on 2022-12-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_remove_student_name_student_email_student_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='exam_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='test_score',
            field=models.IntegerField(default=0),
        ),
    ]
