# Generated by Django 4.1.3 on 2023-01-05 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_rename_student_studentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='exam_score',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='test_score',
        ),
    ]
