# Generated by Django 4.1.3 on 2023-01-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_remove_studentmodel_exam_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/%y/%m'),
        ),
    ]
